project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "ECIV542: Traffic Engineering"
  description: "Homepage for ECIV 542: Traffic Engineering at UofSC, Fall 2026."

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Fahim Ahmed; Inspired from Mine Çetinkaya-Rundel"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/traffic_light_006.jpg"
    pinned: true
    align: center

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home/Announcement
      - href: course-schedule.qmd
        text: Fall 2026 Schedule
      - href: https://blackboard.sc.edu/webapps/login/
        text: Syllabus (Blackboard)
      # - href: course-support.qmd
      #   text: Support
      - href: course-team.qmd
        text: Teaching team
      # - href: course-links.qmd
      #   text: Useful links
      # - href: course-faq.qmd
      #   text: FAQ
      - section: "Project"
        # contents:
        #   - href: project-description.qmd
        #     text: Description
        #   - href: project-tips-resources.qmd
        #     text: Tips + resources
        #   - href: project-tips-resources.qmd
        #     text: Lab Software/Manual
      - section: "Learning materials"
        contents:
          - href: lecture/eciv542syllabusFall26.qmd
            text: "Class 01: Intro & Syllabus"
          - href: lecture/introTrafficEngr.qmd
            text: "Class 01: Ch1- Intro to Traffic Engr."
          - href: lecture/rdUserVehCharacteristics.qmd
            text: "Class 02: Ch2 - Road User and Veh. Characteristics"
          - href: lecture/ch3HorDgn.qmd
            text: "Class 02: Ch3 - Horizontal Design"


      - section: "Supplemental notes"
        # contents:
        #   - href: supplemental/slr-derivations.qmd
        #     text: SLR derivations
        #   - href: supplemental/model-diagnostics-matrix.qmd
        #     text: Model diagnostics
        #   - href: supplemental/mlr-matrix.qmd
        #     text: MLR matrix notation
        #   - href: supplemental/log-transformations.qmd
        #     text: Log transformations
        #   - href: supplemental/model-selection-criteria.qmd
        #     text: Model selection criteria


format:
  html:
    theme:
      light: [cosmo]
      # dark: [cosmo]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: source


