project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "ECIV542: Traffic Engineering"
  description: "Homepage for ECIV 542: Traffic Engineering at UofSC, Fall 2026."

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Fahim Ahmed; Inspired from Mine Çetinkaya-Rundel"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/traffic_light_006.jpg"
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home/Announcement
      - href: course-schedule.qmd
        text: Fall 2026 Schedule
      - href: https://blackboard.sc.edu/webapps/login/
        text: Syllabus (Blackboard)
      - href: course-team.qmd
        text: Teaching team & Support

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Lectures"
        menu:
          - href: lecture/eciv542syllabusFall26.qmd
            text: "19AUG26-Class 01: Intro & Syllabus"
          - href: lecture/introTrafficEngr.qmd
            text: "19AUG26-Class 01: Ch1- Intro to Traffic Engr."
          - href: lecture/rdUserVehCharacteristics.qmd
            text: "24AUG26-Class 02: Ch2 - Road User and Veh. Characteristics"
          - href: lecture/ch3HorDgn.qmd
            text: "26AUG26-Class 03: Ch27 - Horizontal Design"
          - href: lecture/ch3VerDgn.qmd
            text: "31AUG26-Class 04: Ch27 - Vertical Design"
          - href: lecture/ch5TrafficStreamCharacter.qmd
            text: "31AUG26-Class 04: Ch5 - Traffic Stream Characteristics"
          - href: lecture/ch5TrafficStreamCharacter.qmd
            text: "02SEP26-Class 05: Ch5 - Traffic Flow Theory"
          - href: lecture/chX_TrafficFlowTheory.qmd
            text: "09SEP26-Class 06: Traffic Flow Theory"
          - href: lecture/chX_TrafficFlowTheory.qmd
            text: "14SEP26-Class 07: Traffic Flow Theory (Cont.) & Ch 4. Traffic Control Devices"
          - href: lecture/ch4TrafficControlDevices.qmd
            text: "16SEP26-Class 08: Ch. 4 Traffic Control Devices (Cont.)"
          - href: lecture/ch11StatsInTransp.qmd
            text: "16SEP26-Class 09: Ch. 11 Statistical Application in Transportation"
          - href: lecture/ch4Quiz.qmd
            text: "Team Scorecard"
      - text: "supplementary Docs"
        menu:
          - href: lecture/ch11spdDataAnalysis.qmd
            text: Ch11 Spot Speed Analysis
          - href: project-description.qmd
            text: Tech Memo 1
          - href: project-description.qmd
            text: Tech Memo 1

      - text: "Homeworks"
        menu: 
          - href: https://blackboard.sc.edu/webapps/login/
            text: "HW #1"
      - text: "Project"
        menu:
          - href: project-description.qmd
            text: Equipment
          - href: project-description.qmd
            text: Tech Memo 1
          - href: project-description.qmd
            text: Tech Memo 1

      
      # - section: "Lectures"
      #   contents:
      #     - href: lecture/eciv542syllabusFall26.qmd
      #       text: "Class 01: Intro & Syllabus"
      #     - href: lecture/introTrafficEngr.qmd
      #       text: "Class 01: Ch1- Intro to Traffic Engr."
      #     - href: lecture/rdUserVehCharacteristics.qmd
      #       text: "Class 02: Ch2 - Road User and Veh. Characteristics"
      #     - href: lecture/ch3HorDgn.qmd
      #       text: "Class 03: Ch3 - Horizontal Design"
      #     - href: lecture/ch3VerDgn.qmd
      #       text: "Class 03: Ch3 - Vertical Design"
      # - section: "Homeworks (HW)"
      #   contents:
      #     - href: templates/hwTemplate.pdf
      #       text: HW Submission Template
      #     - href: supplemental/model-diagnostics-matrix.qmd
      #       text: HW 1
      # - section: "Project"
      #   contents:
      #     - href: project-description.qmd
      #       text: Equipment
      #     - href: project-description.qmd
      #       text: Tech Memo 1
      #     - href: project-description.qmd
      #       text: Tech Memo 1
      # - section: "Lab"
      #   contents:
      #     - href: project-description.qmd
      #       text: Lab Loc B123 Main
      #     - href: project-description.qmd
      #       text: Tech Memo 1



format:
  html:
    theme:
      light: [cosmo]
      # dark: [cosmo]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: source


